### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by adama2000** [SimplifiedLogic/creoson#1]
Currently the logging of server requests is "always on".  Make a java option such as -Dsli.server.logging to turn logging on, and have it be off by default.

This refers to the logging done in the server project when receiving JSON and HTTP requests.

**Comment by FrostTiger** [comment]
Timer feature can be added to connection request like following code:
``

**Comment by davidhbigelow** [comment]
I think this is a client side decision on the timing of functions/execution duration.
