### ISSUE TITLE
Creoson Object commands

### ISSUE THREAD

**Issue by DieSwartKat** [SimplifiedLogic/creoson#101]
Hi Guys

It has been a while since I updated my creoson knowledge so I decided to go though the functions again and try some of those I haven't been using.

There is a group of function under command : object. None of them are callable through the URL.

[JLTransform Questions](https://github.com/SimplifiedLogic/creoson/issues/94)

The above function is also in that group and there isn't much information further on how to use it.

I've downloaded the latest version of CREOSON, I'm using CREO 3.0

Can anyone help me to use these or explain the purpose and interpretation from the creoson documentation.

**Comment by adama2000** [comment]
All the things under the "object" category are not functions, they are data
objects that are used by other functions either as input or output.  You
would need to look at the documentation for those functions to see how
they're used.

JLTransform represents a 3D transformation matrix, that represents Creo's
Matrix3D or Transform3D objects.

JLTransform is used as input to:

   - file:assemble to specify a transformation for the component after
   assembly -- see the "transform" argument

JLTransform is used as output from:

   - bom:get_paths to find the transforms applied to each component in the
   assembly -- this is actually part of "object : BomChild", which contains a
   "transform" argument.  See the last example on this page of what the return
   looks like.
   - file:get_transform to find the transform applied to a specific
   component in an assembly -- the creoson doc doesn't actually call it a
   JLTransform object, but that's what the return data is.
