### ISSUE TITLE
Windchill List Workspace Files Error

### ISSUE THREAD

**Issue by thackb** [SimplifiedLogic/creoson#102]
Hi
Hope someone can help.

I'm having problems listing the windchill workspace files.

I create and send the following JSON request :-

{"sessionId":"-2590201543981699761","command":"windchill","function":"list_workspace_files","data":{"filename":"a*"}}

All that I get back is
{"status":{"error":true,"message":"No 'workspace' parameter given"},"data":null}

Thanks In Advance..

**Comment by adama2000** [comment]
Sorry for the late response.  That command requires a "workspace" option which contains the name of your workspace.

{"sessionId":"-2590201543981699761","command":"windchill","function":"list_workspace_files","data":{"filename":"a*", "workspace":"my_workspace"}}

**Comment by thackb** [comment]
Thanks works perfectly 👍 :)
