### ISSUE TITLE
Creo 11.0.2.0 Read Parameter Error

### ISSUE THREAD

**Issue by thackb** [SimplifiedLogic/creoson#113]
Im testing Creo 11.0.2.0 with creoson 2.9 and getting the following error reading parameters from files:

xdr_ProParamvalue: Unknown entity type 0

![image](https://github.com/user-attachments/assets/f9ffe542-cad2-4f5d-918d-ab9067d13a56)

**Comment by adama2000** [comment]
I tested Creo 11.0.1.0 with a creoson "parameter list" command and I didn't
get that error.  Is that the creoson command that gives you the error, or
were you using a different function to get the error?

I can try downloading 11.0.2.0 later to try that version.  But I would like
more detail about what creoson functions you're calling.

Thanks,
Adam Andrews

**Comment by thackb** [comment]
Hi Adam

I call the Parameter > List function with :-

{"sessionId":"-738066437541115818","command":"parameter","function":"list","data":{"file":"test.prt","name":"PART_NUMBER"}}


The JSON I get back from the function is :-

{"status":{"error":true,"message":"Cannot get parameter value using obsolete function; check that your PATH contains only one version of Creo"},"data":null}

**Comment by thackb** [comment]
I have found the problem. My Fault :(
  
A Windows Enviorment Settings 

set PROE_COMMON=D:\PTC\Creo 11.0.2.0\Common Files

All working as normal now
