### ISSUE TITLE
Function Drawing Symbol_File

### ISSUE THREAD

**Issue by dmtr99** [SimplifiedLogic/creoson#16]
The function list_symbols returns the error:
"No 'symbol_file' parameter given"
When leaving the symbol_file empty.

When specifiïng the symbol, the function works perfect.

**Comment by adama2000** [comment]
That's a bug, thanks for pointing that out.  The function ought to support an empty symbol_file.

**Comment by adama2000** [comment]
Checked in a fix for this issue, the fix will be included in the next release.
