### ISSUE TITLE
UNICODE support

### ISSUE THREAD

**Issue by YaroslavSin** [SimplifiedLogic/creoson#2]
I'm playing with Playground and found that the search by parameters not working with names of parameter in cyrillic. The same problem with string value in cyrillic.

**Comment by adama2000** [comment]
Hm, can you give us a test case?  Such as a sample part and a test application which shows the problem?

**Comment by YaroslavSin** [comment]
https://cloud.mail.ru/public/AKXD/kayyR7RTN

Part for testing.
Parameters:
TEST_RU_VALUE = Строка текста на русском
ТЕСТ_РУ_ЗНАЧЕНИЕ = Test ru text
ПРОВЕРКА = значение провеки

**Comment by adama2000** [comment]
Thanks, we're working on the issue.

**Comment by adama2000** [comment]
Fix is posted to the source repository, and included in the 2.1.0 release just published.  This was not a Playground issue but an issue with the core code which was not dealing with Unicode characters properly.
