### ISSUE TITLE
Create a new part

### ISSUE THREAD

**Issue by curiosity-rover** [SimplifiedLogic/creoson#20]
Is it possible to create a new part (without having to use mapkeys)?

**Comment by curiosity-rover** [comment]
**Current method:**
filename="tempfile1"
xyz="~ Command `ProCmdModelNew` ;~ Input `new` `InputPanel1`  "+"`"+filename+"`;"+"~ Select `new` `Type` 1 `Part`;~ Activate `new` `OK`;"
c.interface_mapkey(xyz)

I'm going to close this, as I was able to pass 'filename' as a string.

**Comment by adama2000** [comment]
No, the JLink API does not support the creation of parts (or the creation of a lot of other things), therefore creoson doesn't support it.
