### ISSUE TITLE
dimension : list_detail

### ISSUE THREAD

**Issue by andersonfelizari** [SimplifiedLogic/creoson#23]
In the function "dimension : list_detail" only is returning the fields "name", "value", "encoded" and "sheet" and in this case would need the "tolerance_type", "tol_plus" and "tol_minus". 

Any idea?

**Comment by andersonfelizari** [comment]
I was looking for PRT and would have to be from DRW.

tranks

**Comment by adama2000** [comment]
Yes, the "detailed" dimension info is only returned for Drawings.  That includes the Tolerances.

**Comment by adama2000** [comment]
I'll update the function doc on the next release to reflect that.
