### ISSUE TITLE
file:get_active don't work as expected

### ISSUE THREAD

**Issue by maywil** [SimplifiedLogic/creoson#3]
Hello!
I found a small problem in this interesting tool.
The function file:get_active should give the dirname complete with the drive name but the drive name is missing. On the other hand the function file:get_fileinfo works as expected!  
Regards,
Wilhelm

**Comment by adama2000** [comment]
You're right.  We'll fix that.

**Comment by adama2000** [comment]
Posted a fix to the source code.  This will be included in the next build, which should happen soon.

**Comment by adama2000** [comment]
Included in newly published release.
