### ISSUE TITLE
Windchill clear_workspace raising error but do the job ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by Zepmanbc** [SimplifiedLogic/creoson#37]
Hi!
I'm using the `windchill` command with `clear_workspace` function to delete 1 file.
Here is the request:
```
{
    'sessionId':'5170641809148701105',
    'command':'windchill',
    'function':'clear_workspace',
    'data':{
        'workspace': 'test_workspace',
        'filenames': ['toto_02.prt']
	}
}
```
the file 'toto_02.prt' is well deleted but it returns me a message error:
```
{status: {
    'error':True,
    'message':'A Pro/TOOLKIT error has occurred: Found.  Check your model/drawing for accuracy.'
    }
}
```

it works fine but I don't understand why there is an error returned.

PS: Do you think it is possible to use wildcard selection for choosing files instead of a list? ( like "toto_*.prt")

**Comment by adama2000** [comment]
I'm guessing that Creo is returning a "Found" error to indicate that it found the file -- which is not really an error.  I need to modify the creoson function to ignore any "Found" errors it gets.

**Comment by Zepmanbc** [comment]
that would be great, thanks!

**Comment by adama2000** [comment]
I'll think about the wildcard option.  That would require looping through all the files in the workspace to find out which ones match, and that would take a while on a large workspace.

**Comment by adama2000** [comment]
I've checked in code to ignore the "Found" error on clear_workspace, so the change will be in the next release.

**Comment by Zepmanbc** [comment]
great
thank you :pray:
