### ISSUE TITLE
Request for faults when opening multiple CREO items.

### ISSUE THREAD

**Issue by DieSwartKat** [SimplifiedLogic/creoson#39]
We are using the wildcard functionality in the CREOSON file open command:

`{'command': 'file', 'function': 'open', 'sessionId': '9083350336389293788', 'data': {'file': '*.drw', 'display': True, 'activate': False, 'regen_force': True, 'new_window': True}}`

The problem with this method is that sometimes we have an issue when drawings do not open. Like if someone renamed a part in a drawing and the drawing is not updated. Also, errors like simplified reps that are in drawing that are missing causes this message when manually opening drawings:

![image](https://user-images.githubusercontent.com/49644543/73340678-db8fba00-4283-11ea-9a67-b6aa7752bc31.png)

Users will have to open each manually, which is kind of pointless.

Would it be possible to at the very least get CREOSON to return the error lists of the components /drawings which were true to *.drw but didn't open?

**Comment by adama2000** [comment]
There is a creoson function "open_errors" which might help.  You can call it with a file and it will return true if any errors occurred.

If you don't know the file names, you could use file.list with the same wildcard argument you used for file.open.

![image](https://user-images.githubusercontent.com/1766716/73396293-122efa00-42af-11ea-90d7-d16cd477b803.png)
