### ISSUE TITLE
feature: supress

### ISSUE THREAD

**Issue by Zepmanbc** [SimplifiedLogic/creoson#46]
Hello,

There is something i don't understand with *feature suppress*

the param `with_children` should suppress all the children of the function.
the param `clip` should suppress everything after the function (whether children or not).

Why the result is an error? With `clip=True` it should suppress everything without arguing?

request:
```
{
    'command': 'feature',
    'data': {
        'clip': True,
        'feat_id': 191,
        'file': 'myfile.prt',
        'with_children': True
    },
    'function': 'suppress',
    'sessionId': '-253955298917346268'
}
```
result:
```
{
    'status': {
        'error': True,
        'message': 'A Pro/TOOLKIT error has occurred: General Error.  Check your model/drawing for accuracy..'
    }
}
```
(feat 191 got children)

If i try to suppress another function, i don't get errors but `with_children` or `clip` params don't change anything on other functions.

**Edit**:
here is an exemple:
![creotree](https://user-images.githubusercontent.com/10487746/75871111-55c7d700-5e0c-11ea-8889-5ad21b506708.png)
Children of *Extrusion 2* are *Chanfrein 1* and *Arrondi 2*

What I expect: (sorry, i use python code for lisibility)
```
c.feature_suppress(name=191, with_children=False, clip=False) => error

c.feature_suppress(name=191, with_children=True, clip=False) => feat 191/220/280 suppressed

c.feature_suppress(name=191, with_children=False, clip=True) => feat 191/220/242/280 suppressed
```

**Comment by davidhbigelow** [comment]
Hmmm..

The defaults for this function are:

with_children = true
clip = true

Which seems to be what you are requesting... but your expected response does not seem to indicate the request being made... 

I did a similar test with a test model we have:
![2020-03-04 at 11 15 AM](https://user-images.githubusercontent.com/1648805/75899508-9f62f280-5e09-11ea-9569-cd460053e5ae.png)

Here is the code (sorry JavaScript):

![2020-03-04 at 11 14 AM](https://user-images.githubusercontent.com/1648805/75899302-5ca11a80-5e09-11ea-852e-aa4ab77e66d7.png)



And here was the resulting output:
![2020-03-04 at 11 12 AM](https://user-images.githubusercontent.com/1648805/75899197-37aca780-5e09-11ea-9d58-9bfba77dde80.png)



The function seems to work -- can you supply your test model - or more resolution on the test you ar running?   What version / build of Creo?

Dave

**Comment by davidhbigelow** [comment]
Oh - I also went and forced the specify of the file in the call...  same result...

![2020-03-04 at 11 22 AM](https://user-images.githubusercontent.com/1648805/75900197-8d358400-5e0a-11ea-8b5d-796abe02d7ea.png)

And without forcing the options:
![2020-03-04 at 11 23 AM](https://user-images.githubusercontent.com/1648805/75900290-b48c5100-5e0a-11ea-87ce-946e347a76c2.png)

And as a triple check - just including only the feature_id  (assumes active model)

![2020-03-04 at 11 24 AM](https://user-images.githubusercontent.com/1648805/75900416-e2719580-5e0a-11ea-9ead-cb675fcdfffc.png)


One small suggestion (style thing for automating creo) -- naming features might be more handy for automation if you can do that... (helps protect against feat_ids getting messed up when expected in code if your creo model changes with a new feature by a user later).

**Comment by davidhbigelow** [comment]
Could there be a relation dependent on these features that is failing when suppressed?

**Comment by adama2000** [comment]
With "clip" we just pass that flag on to Creo as an argument to JLink's SuppressOperation class, which is sent to their suppress function.

With "with_children", we use that internally.  If that's set to true, we walk our way down all the child features of the original feature and add them to a total list.  Only at the end do we suppress the whole list of features.

The error you're getting is coming from Creo, not us, so there must be something about the model that's causing the suppress to fail when clip is turned on.

**Comment by Zepmanbc** [comment]
Thanks, i'll investigate.

**Comment by Zepmanbc** [comment]
I've tried with Creoson 2.4 64bits and it works better than 2.5...

I had to rename the function because feat_id was implemented in 2.5

![image](https://user-images.githubusercontent.com/10487746/75973575-ad7e4500-5ed5-11ea-8925-f83f0bd56ce1.png)

`c.feature_suppress(name="EXTRU", with_children=False, clip=False)` => error as expected

`c.feature_suppress(name="EXTRU", with_children=False, clip=True)` => feat 191/220/280 suppressed
![image](https://user-images.githubusercontent.com/10487746/75973866-30070480-5ed6-11ea-9671-987e3c96e58b.png)
not as expected, 242 is still active

`c.feature_suppress(name="EXTRU", with_children=True, clip=True)` => feat 191/220/280 suppressed, the same as above

`c.feature_suppress(name="EXTRU", with_children=True, clip=False)` => error

it seems that *clip* is required and *with_children* has no incidence.

I use Creo 4.0 M110 on Windows 10

**Comment by adama2000** [comment]
After testing with your part, I found a bug in the creoson code where if you specified a feat_id instead of a name, the "clip" flag was NOT properly being passed to Creo, so it was behaving as if clip was always false.  I'll check in a fix for that into creoson.

**Comment by adama2000** [comment]
Will that answer the situation or are there still things besides that which aren't working right?

**Comment by adama2000** [comment]
I've checked the bug fix in to github

**Comment by Zepmanbc** [comment]
Hi Adam,
Thanks for looking at this issue
I don't know if it's a normal way to work but the "with children" in
feature resume seems to not reactivate children functions.
It means that if I want to resume 191 with "with_chldren=True", 220 and 280
are still desactivated

**Comment by adama2000** [comment]
... you've uncovered another bug.  I think this bug also explain why you sometimes get errors on the suppress when clip=false but with_children=true.

The bug is that the with_children handling is skipping over unnamed features due to an internal flag setting.  I'll fix that when I do some more testing.

**Comment by adama2000** [comment]
I've pushed the new fix to creoson github.

**Comment by Zepmanbc** [comment]
Thanks @adama2000 

I've compiled the new version and done some tests:

`c.feature_suppress(name="EXTRU", clip=True, with_children=True)` => supress 191/220/242
`c.feature_suppress(name="EXTRU", clip=True, with_children=False)` => supress 191/220/242
`c.feature_suppress(name="EXTRU", clip=False, with_children=True)` => supress 191/220/242
`c.feature_suppress(name="EXTRU", clip=False, with_children=False)` => error

`c.feature_suppress(name=191, clip=True, with_children=True)` => supress 191/220/242
`c.feature_suppress(name=191, clip=True, with_children=False)` => supress 191/220/242
`c.feature_suppress(name=191, clip=False, with_children=True)` => supress 191/220/242
`c.feature_suppress(name=191, clip=False, with_children=False)` => error

`c.feature_resume(name=191, with_children=True)` => resume all
`c.feature_resume(name=191, with_children=False)` => resume only 191
`c.feature_resume(name="EXTRU", with_children=True)` => resume all
`c.feature_resume(name="EXTRU", with_children=False)` => resume only 191

*feat_id* and *name* do the same now
but I still don't see difference between *with_children* and *clip*
I thought that *clip=True* would have suppress 242, am i wrong?

![image](https://user-images.githubusercontent.com/10487746/76074671-02848e80-5f9c-11ea-8565-b25a70c4320a.png)

**Comment by adama2000** [comment]
Here's the JLink doc for what "clip" does: "A Boolean flag that specifies
whether to suppress the selected feature and all the features that follow.
Default value is false."

The question is, what does Creo mean by "the features that follow"?

Feature 242 is not a child of Feature 191, so I wouldn't think it would be
suppressed normally.

Adam

**Comment by adama2000** [comment]
With the bug fixes newly released, can this be closed?

**Comment by Zepmanbc** [comment]
Yes, thanks
you're right, what is a feature "that follow"...
