### ISSUE TITLE
Model Properties : Accuracy

### ISSUE THREAD

**Issue by Zepmanbc** [SimplifiedLogic/creoson#51]
Hi

Is it possible to get current **Accuracy** of a model?
the *value* and if it is *Relative* or *Absolute*

Thank you

**Comment by adama2000** [comment]
Yes it would be possible, we could return both relative and absolute accuracy values.  Doing so would be an enhancement.

Maybe it would be a single "get_accuracy" function which took a boolean argument which said whether you wanted absolute or relative accuracy?  Or should it be two separate functions?

**Comment by adama2000** [comment]
Actually, maybe it should be a single function which returned both accuracy values.

**Comment by adama2000** [comment]
I took a closer look at the Creo documentation -- it says that only one or the other value is given, not both.  So it would be one function that returns a single value plus a relative/absolute flag as you said.

**Comment by Zepmanbc** [comment]
That would be perfect the value plus the flag

Le ven. 10 juil. 2020 à 19:52, adama2000 <notifications@github.com> a
écrit :

**Comment by adama2000** [comment]
I checked in the file.get_accuracy function.  Appears to work for me, though I couldn't find a model with absolute accuracy for testing.

**Comment by adama2000** [comment]
Now tested with an absolute-accuracy model.  Thanks @Zepmanbc
