### ISSUE TITLE
Java version for creoson

### ISSUE THREAD

**Issue by FrostTiger** [SimplifiedLogic/creoson#6]
Which java version should I use? Normally I have used Java version 1.8.0_144. Server works perfect but System.loadLibrary("pfcasyncmt") is not working in JLGlobal class. When I check library version that released in github.  I realized that 1.7.0_65 is used.  If I changed java version to 1.7. This time server wasn't started. I need to know exact version of java for working properly on it.
Thanks in advance

**Comment by FrostTiger** [comment]
I found what the problem is. Main cause is platform mismatch. I added pfcasyncmt.dll to system path and it works properly.

**Comment by adama2000** [comment]
Yes, the DLL does need to be in your system path for this to work.
