### ISSUE TITLE
Interface : mapkey function

### ISSUE THREAD

**Issue by DG1987** [SimplifiedLogic/creoson#7]
I'm having issue's with the interface : mapkey function.
It works to play the first line, but nothing happens for the lines on the next command.

It is also possible to play it line by line, but the end result is slow...

Can somebody  check if they are having the same problem?

Is there something missing in the explanation to add the next line:
( i have replaced the signs for the example in " because of the automatic Styling on github)
{
  "sessionId": "`~`sessionId`~`",
  "command": "interface",
  "function": "mapkey",
  "data": {
    "script": "`~` Select "main_dlg_cur" "View:casc340798662";mapkey(continued) ~ Close "main_dlg_cur" "View:casc340798662";mapkey(continued) ~ Command "ProCmdNamedViewsGalSelect"  "FRONT";"
  }
}

**Comment by adama2000** [comment]
Try taking out the "mapkey(continued)" parts from the middle, see if that helps.  When using the "interface:mapkey" function, the tildes should come right after the previous semicolon, like this:

"script":"~ Select "main_dlg_cur" "View:casc340798662";~ Close "main_dlg_cur" "View:casc340798662";~ Command "ProCmdNamedViewsGalSelect" "FRONT";"

**Comment by DG1987** [comment]
Perfect, It works if I remove "mapkey(continued)"
I will contact documentation with a request to change it.

**Comment by adama2000** [comment]
Checked in a doc change for interface:mapkey to warn users about the issue.
