### ISSUE TITLE
CREO UI Automation

### ISSUE THREAD

**Issue by DieSwartKat** [SimplifiedLogic/creoson#70]
Hi Guys

We use CREOSON on a daily basis to help our engineers do great work, thanks so much for making it available. Would it be possible to add to CREOSON functions that can add icons to the CREO UI which activate a mapkeys?

**Comment by davidhbigelow** [comment]
Sorry - no - that out of the scope of CREOSON's intended use.

We have had that request come up before with our commercial products, but as external apps (like CREOSON is also) it is a bit convoluted.

**Comment by DieSwartKat** [comment]
Thanks for the feedback David.
