### ISSUE TITLE
Get Path of active files

### ISSUE THREAD

**Issue by DieSwartKat** [SimplifiedLogic/creoson#77]
Hallo Guys

Does anyone know if there is a way to get the path (folder directory in windows) to a part or assembly that is open in CREO at the moment. I'm specifically looking for parts that are not in the working directory, but has been assembled into the model.

I'm assuming the drawing of that part will be in the same folder and therefore want to know the folder so that I can find the drawings.

**Comment by phaleth** [comment]
Hi,

Not sure about Creoson, but for J-Link I've found two following examples that are sort of interchangeable.

```java
Window currentWindow = session.GetCurrentWindow();
Model currentModel = currentWindow.GetModel();
ModelDescriptor currModelDescr = currentModel.GetDescr();
// Path without the disk letter, without colon
// and with trailing backslash
String fullPath = currModelDescr.GetPath();
```

```java
Model activeModel = session.GetActiveModel();
ModelDescriptor actModelDescr = activeModel.GetDescr();
// Full path without trailing backslash
String fullPath = actModelDescr.GetDevice() + ":" + actModelDescr.GetPath();
```

**Comment by adama2000** [comment]
Yes, the file : get_fileinfo should work, it returns file, dirname, and revision for the requested model.
