### ISSUE TITLE
Adding a table to a drawing sheet

### ISSUE THREAD

**Issue by dummifiedme** [SimplifiedLogic/creoson#88]
While working on a drawing sheet, I noticed that I am unable to create a table using creoson or creopyson. 

Is there a way to create a table in a drawing sheet using the library and its functions?

**Comment by Zepmanbc** [comment]
Sorry, never tried this
ask your question on [Creoson's page](https://github.com/SimplifiedLogic/creoson/issues)

**Comment by davidhbigelow** [comment]
Mapkeys may be the best option for this type of operation. (sorry for the long response - just noticed it) :(
